name: zerotier-planet-images
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *' # 每天的 0 点执行
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Check update
        run: |
          chmod +x ./checkUpdate.sh
          zt_v=$(./checkUpdate.sh)
          echo "ZT_VERSION=$zt_v" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v6
        if: ${{ env.ZT_VERSION != 'none' }}
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
          push: true
          tags: sknehc/zerotier-planet:${{ env.ZT_VERSION }}
          args: |
            --build-arg TAG=${{ env.ZT_VERSION }}
